package psg.facilitei.DTO;

import java.util.List;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class TrabalhadorRequestDTO {

    @NotBlank
    private String nome;
    @NotBlank
    @Email
    private String email;
    // Renamed for consistency and clarity:
    private EnderecoRequestDTO endereco; // Changed from EnderecoResponseDTO EnderecoResponseDTO
    private List<Long> servicosIds;
    private List<Long> avaliacoesIds;
    private Integer notaTrabalhador;
    private String senha; // Getter/setter generated by Lombok
}